image: finanzcheck/docker-node-java

variables:
  ANDROID_COMPILE_SDK: "28"
  ANDROID_BUILD_TOOLS: "28.0.2"
  ANDROID_SDK_TOOLS:   "4333796"

stages:
  - install_dependencies
  - test
  - pull_upstream
  - rebase
  - build_android

cache:
  paths:
    - node_modules/
    - dist/

install_dependencies:
  stage: install_dependencies
  script:
    - make pre-run
    - cd node_modules/mattermost-redux && npm install 
    - npm run build
    - cd ../../
    - make dist/assets
  artifacts:
    paths:
      - node_modules/
      - dist/

run_unit_tests:
  stage: test
  script:
    - find dist/assets/ -name config.json
    - make check-style 
    - npm test

pull_master_upstream:
  stage: pull_upstream
  only:
    - schedules 
  script:
    - git clone https://andre.tito:andretito14@dev.architectgroup.com/argp/mchat/mchat-mobile.git
    - cd *mobile
    - git remote add upstream https://github.com/mattermost/mattermost-mobile.git
    - git pull upstream master
    - git push origin master

rebase_to_master:
  stage: rebase
  only:
    - schedules

  script:
    - git clone https://andre.tito:andretito14@dev.architectgroup.com/argp/mchat/mchat-mobile.git
    - cd *mobile
    - git checkout develop
    - git rebase origin/master
    - git push --force origin develop

build_android:
  stage: build_android
  only:
    - schedules
  before_script:
    - apt-get --quiet update --yes
    - apt-get --quiet install --yes wget tar unzip lib32stdc++6 lib32z1
    - wget --quiet --output-document=android-sdk.zip https://dl.google.com/android/repository/sdk-tools-linux-${ANDROID_SDK_TOOLS}.zip
    - unzip -d android-sdk-linux android-sdk.zip
    - echo y | android-sdk-linux/tools/bin/sdkmanager "platforms;android-${ANDROID_COMPILE_SDK}" >/dev/null
    - echo y | android-sdk-linux/tools/bin/sdkmanager "platform-tools" >/dev/null
    - echo y | android-sdk-linux/tools/bin/sdkmanager "build-tools;${ANDROID_BUILD_TOOLS}" >/dev/null
    - export ANDROID_HOME=$PWD/android-sdk-linux
    - export PATH=$PATH:$PWD/android-sdk-linux/platform-tools/
    - cd android && chmod +x ./gradlew
  script:
    - git checkout develop
    - ./gradlew assembleRelease
